INSERT INTO ROLE (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Tester', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ROLE (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Application Developer', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ROLE (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Director', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ROLE (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Business Development Manager', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO ACCESS (NAME, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Test Access', 'TEST ACCESS DESCRIPTION', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ACCESS (NAME, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('No Access', 'NO ACCESS DESCRIPTION', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ACCESS (NAME, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Read Only', 'READ ONLY ACCESS DESCRIPTION', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ACCESS (NAME, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Full', 'FULL ACCESS DESCRIPTION', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO USER (ROLE_ID, ACCESS_ID, USERNAME, FIRSTNAME, LASTNAME, NAME, PASSWORD, PASSWORDUPDATEDON, EMAILADDRESS, PHONENUMBER, ADDRESS, CITY, STATE, COUNTRY, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 1, 'wbohrer', 'Willem', 'Bohrer', 'Willem Bohrer', CRYPT('WillemPass', GEN_SALT('bf')), NOW()::TIMESTAMPTZ(0), 'WillemBohrer@Outlook.com', '(555) 555-5555', 'Dakota Drive North', 'Fargo', 'North Dakota', 'USA', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO SUB_CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Company Profile', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Company History', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Passwords', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Virus Protection', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Vendor Business Information', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Application Security', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('System & Network Security', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Access Control', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Company Information', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO CATEGORY_DETAILS (CATEGORY_ID, SUB_CATEGORY_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY_DETAILS (CATEGORY_ID, SUB_CATEGORY_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY_DETAILS (CATEGORY_ID, SUB_CATEGORY_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY_DETAILS (CATEGORY_ID, SUB_CATEGORY_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (4, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CATEGORY_DETAILS (CATEGORY_ID, SUB_CATEGORY_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO SOURCE (NAME, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Internal', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 'Do you use an automated or manual source code analysis tool to detect security defects in code prior to production?', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 'Operating system and email Antivirus software is used, monitored, and updated.  This includes workstations and servers.', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (4, 'Are initial passwords communicated to users via the following method(s):', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 'Is the application internet available?', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 'Has the Application been subjected to a 3rd party penetration test?', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION (SOURCE_ID, DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 'Has your company acquired any company during the past 7 years?', 'No Description', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

NSERT INTO ANSWER (DESCRIPTION, RESPONDENT, RESPONSEON, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Yes, . . .', 'Willem Bohrer', NOW()::TIMESTAMPTZ(0), NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ANSWER (DESCRIPTION, RESPONDENT, RESPONSEON, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('No, . . .', 'Jack Olson', NOW()::TIMESTAMPTZ(0), NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ANSWER (DESCRIPTION, RESPONDENT, RESPONSEON, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Yes, . . .', 'Vaughan Johnson', NOW()::TIMESTAMPTZ(0), NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ANSWER (DESCRIPTION, RESPONDENT, RESPONSEON, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('No, . . .', 'Willem Bohrer', NOW()::TIMESTAMPTZ(0), NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Encrpted/Secure e-mail?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Telephone call?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Instant Messaging?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Cell phone text Message?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Paper Document?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO SUB_QUESTION (DESCRIPTION, COMMENTS, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Verbal?', 'Type of Communication needed', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 1, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 2, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (4, 4, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (5, 5, 5, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (6, 5, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (7, 4, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (7, 3, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (6, 2, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO QUESTION_DETAILS (QUESTION_ID, ANSWER_ID, SUB_QUESTION_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (5, 1, 5, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO ARTICLE (TYPE, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('RFI', 'Request for Information', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ARTICLE (TYPE, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('RFP', 'Request for Proposal', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ARTICLE (TYPE, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Security', 'Request for Security Information', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO ARTICLE (TYPE, DESCRIPTION, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Business', 'Request for Business Information', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO REQUESTOR (NAME, TYPE, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES ('Business Name', 'PROSPECT', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO CONTACT (REQUESTOR_ID, FIRSTNAME, LASTNAME, NAME, EMAILADDRESS, PHONENUMBER, ADDRESS, CITY, STATE, COUNTRY, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 'Percival', 'Jackson', 'Percy Jackson', 'Percy.Jackson@NDSU.edu', '(218)822-5489', '217 Forest Drive', 'Minneapolis', 'Minnesota', 'USA', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CONTACT (REQUESTOR_ID, FIRSTNAME, LASTNAME, NAME, EMAILADDRESS, PHONENUMBER, ADDRESS, CITY, STATE, COUNTRY, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 'Michael', 'Reeves', 'Michael Reeves', 'Michael.Reeves@NDSU.edu', '(218)733-3124', '1600 Pennsylvania Ave NW', 'Washington ', 'Washington DC', 'USA', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CONTACT (REQUESTOR_ID, FIRSTNAME, LASTNAME, NAME, EMAILADDRESS, PHONENUMBER, ADDRESS, CITY, STATE, COUNTRY, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 'Linus', 'Sebastian', 'Linus Sebastian', 'Linus.Sebastian@NDSU.edu', '(218)644-0459', '1600 Amphitheatre Parkway', 'Mountain View', 'California', 'USA', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO CONTACT (REQUESTOR_ID, FIRSTNAME, LASTNAME, NAME, EMAILADDRESS, PHONENUMBER, ADDRESS, CITY, STATE, COUNTRY, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (4, 'Julian ', 'Baumgartner', 'Julian Baumgartner', 'Julian.Baumgartner@NDSU.edu', '(218)555-0234', '226 4th St N', 'Fargo', 'North Dakota', 'USA', NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);

INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (1, 1, 1, 1, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 1, 1, 2, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 2, 1, 3, 1, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 2, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 3, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 3, 1, 4, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 2, 1, 2, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (3, 2, 1, 2, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
INSERT INTO KNOWLEDGE (ARTICLE_ID, REQUESTOR_ID, CATEGORY_DETAILS_ID, QUESTION_DETAILS_ID, CAPTURIS_USER_ID, CREATEDON, CREATEDBY, LASTUPDATEON, LASTUPDATEDBY, ACTIVE)
  VALUES (2, 4, 1, 5, 4, NOW()::TIMESTAMPTZ(0), 'willembohrer', NOW()::TIMESTAMPTZ(0), 'willembohrer', TRUE);
