DROP TABLE ANSWER CASCADE;
DROP TABLE SUB_QUESTION CASCADE;
DROP TABLE QUESTION CASCADE;
DROP TABLE SOURCE CASCADE;
DROP TABLE ARTICLE CASCADE;
DROP TABLE ROLE CASCADE;
DROP TABLE ACCESS CASCADE;
DROP TABLE SUB_CATEGORY CASCADE;
DROP TABLE CATEGORY CASCADE;
DROP TABLE USER CASCADE;
DROP TABLE CONTACT CASCADE;
DROP TABLE REQUESTOR CASCADE;
DROP TABLE KNOWLEDGE CASCADE;
DROP TABLE QUESTION_DETAILS CASCADE;
DROP TABLE CATEGORY_DETAILS CASCADE;

DROP EXTENSION PGCRYPTO;
CREATE EXTENSION PGCRYPTO;

CREATE TYPE
  REQUESTOR_TYPE
AS ENUM
  ('PROSPECT', 'CHANNEL_PARTNER', 'CUSTOMER', 'MISC');

CREATE TABLE ROLE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ACCESS(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  DESCRIPTION VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE USER(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  ROLE_ID INT DEFAULT 4 NOT NULL,
  CONSTRAINT FK_ROLE_ID
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID),
  ACCESS_ID INT DEFAULT 3 NOT NULL,
  CONSTRAINT FK_ACCESS_ID
    FOREIGN KEY(ACCESS_ID) REFERENCES ACCESS(ID),
  FIRSTNAME VARCHAR,
  LASTNAME VARCHAR,
  NAME VARCHAR,
  USERNAME VARCHAR NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  PASSWORDUPDATEDON TIMESTAMPTZ (0),
  EMAILADDRESS TEXT NOT NULL UNIQUE,
  PHONENUMBER VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY  VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE SUB_CATEGORY(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE CATEGORY(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE CATEGORY_DETAILS(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  CATEGORY_ID INT NOT NULL,
  CONSTRAINT FK_CATEGORY_ID
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID),
  SUB_CATEGORY_ID INT NOT NULL,
  CONSTRAINT FK_SUB_CATEGORY_ID
    FOREIGN KEY(SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY(ID),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE SOURCE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE QUESTION(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  SOURCE_ID INT NOT NULL,
  CONSTRAINT FK_SOURCE_ID
    FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID),
  DESCRIPTION VARCHAR,
  COMMENTS VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ANSWER(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  DESCRIPTION VARCHAR,
  RESPONDENT VARCHAR,
  RESPONSEON TIMESTAMPTZ (0),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE SUB_QUESTION(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  DESCRIPTION VARCHAR,
  COMMENTS VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE QUESTION_DETAILS(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  QUESTION_ID INT NOT NULL,
  CONSTRAINT FK_QUESTION_ID
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID),
  ANSWER_ID INT NOT NULL,
  CONSTRAINT FK_ANSWER_ID
    FOREIGN KEY(ANSWER_ID) REFERENCES ANSWER(ID),
  SUB_QUESTION_ID INT NOT NULL,
  CONSTRAINT FK_SUB_QUESTION_ID
    FOREIGN KEY(SUB_QUESTION_ID) REFERENCES SUB_QUESTION(ID),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ARTICLE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  TYPE VARCHAR,
  DESCRIPTION VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE REQUESTOR(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  TYPE REQUESTOR_TYPE,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE CONTACT(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  REQUESTOR_ID INT NOT NULL,
  CONSTRAINT FK_REQUESTOR_ID
    FOREIGN KEY(REQUESTOR_ID) REFERENCES REQUESTOR(ID),
  FIRSTNAME VARCHAR,
  LASTNAME VARCHAR,
  NAME VARCHAR,
  EMAILADDRESS TEXT NOT NULL UNIQUE,
  PHONENUMBER VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE KNOWLEDGE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  ARTICLE_ID INT NOT NULL,
  CONSTRAINT FK_ARTICLE_ID
    FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID),
  REQUESTOR_ID INT NOT NULL,
  CONSTRAINT FK_REQUESTOR_ID
    FOREIGN KEY(REQUESTOR_ID) REFERENCES REQUESTOR(ID),
  CATEGORY_DETAILS_ID INT NOT NULL,
  CONSTRAINT FK_CATEGORY_DETAILS_ID
    FOREIGN KEY(CATEGORY_DETAILS_ID) REFERENCES CATEGORY_DETAILS(ID),
  QUESTION_DETAILS_ID INT NOT NULL,
  CONSTRAINT FK_QUESTION_DETAILS_ID
    FOREIGN KEY(QUESTION_DETAILS_ID) REFERENCES QUESTION_DETAILS(ID),
  USER_ID INT NOT NULL,
  CONSTRAINT FK_USER_ID
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);
