--DROP ALL TABLES AND DELETE ALL RELATED INFORMATION, WITHOUT DELETING DATABASE CONFIGURATIONS
DROP TABLE ROLE CASCADE;
DROP TABLE ACCESS CASCADE;
DROP TABLE STUDENT CASCADE;
DROP TABLE ATTENDANCE CASCADE;
DROP TABLE ROOM CASCADE;
DROP TABLE ROLE CASCADE;
DROP TABLE ROOM_SCHEDULE CASCADE;
DROP TABLE CLASS CASCADE;
DROP TABLE PROFESSOR CASCADE;

--EXTENSION USED FOR PASSWORD ENCRYPTION
DROP EXTENSION PGCRYPTO;
CREATE EXTENSION PGCRYPTO;

CREATE TABLE ROLE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ACCESS(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  DESCRIPTION VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PROFESSOR(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  ROLE_ID INT DEFAULT 1 NOT NULL,
  CONSTRAINT FK_ROLE_ID
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID),
  ACCESS_ID INT DEFAULT 1 NOT NULL,
  CONSTRAINT FK_ACCESS_ID
    FOREIGN KEY(ACCESS_ID) REFERENCES ACCESS(ID),
  FIRSTNAME VARCHAR,
  LASTNAME VARCHAR,
  NAME VARCHAR,
  USERNAME VARCHAR NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  PASSWORDUPDATEDON TIMESTAMPTZ (0),
  EMAILADDRESS TEXT NOT NULL UNIQUE,
  PHONENUMBER VARCHAR,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ROOM(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  BUILDING VARCHAR,
  NUMBER VARCHAR DEFAULT 0,
  CAPACITY INTEGER DEFAULT 0,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ROOM_SCHEDULE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  ROOM_ID INT DEFAULT 1 NOT NULL,
  CONSTRAINT FK_ROOM_ID
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
  STARTTIME TIMESTAMPTZ (0),
  ENDTIME TIMESTAMPTZ (0),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE CLASS(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  PROFESSOR_ID INT NOT NULL,
  CONSTRAINT FK_PROFESSOR_ID
    FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID),
  ROOM_SCHEDULE_ID INT NOT NULL,
  CONSTRAINT FK_ROOM_SCHEDULE_ID
    FOREIGN KEY(ROOM_SCHEDULE_ID) REFERENCES ROOM_SCHEDULE(ID),
  NAME VARCHAR,
  NUMBER VARCHAR,
  SECTION INTEGER,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE STUDENT(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  NAME VARCHAR,
  EMAILADDRESS TEXT NOT NULL UNIQUE,
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE ATTENDANCE(
  ID SERIAL NOT NULL,
  PRIMARY KEY(ID),
  STUDENT_ID INT NOT NULL,
  CONSTRAINT FK_STUDENT_ID
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID),
  ROOM_SCHEDULE_ID INT NOT NULL,
  CONSTRAINT FK_ROOM_SCHEDULE_ID
    FOREIGN KEY(ROOM_SCHEDULE_ID) REFERENCES ROOM_SCHEDULE(ID),
  CREATEDON TIMESTAMPTZ (0),
  CREATEDBY VARCHAR,
  LASTUPDATEON TIMESTAMPTZ (0),
  LASTUPDATEDBY VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE
);
