--Functions for showing Database functionality.
--Drop All Tables
DROP TABLE REPAIR, EMPLOYEE, VEHICLE, ORDERS, LOCATION, CUSTOMER;

--Repair History
SELECT
  CONCAT (C.FIRSTNAME, ' ', C.LASTNAME) AS "Customer Name:",
  CONCAT ('Year: ', CAST(V.YEAR AS VARCHAR), ', Make: ' , V.MAKE, ', Model: ' , V.MODEL,
    ', License Plate: ', V.LICENSEPLATE) AS "Vehicle Information:",
  R.REPAIRDATE AS "Date Repaired:",
  CONCAT('$', (R.LABOR * E.HOURLYRATE)) AS "Cost of Repair:",
  CONCAT('Part Name: ', O.PARTNAME, ', Quantity: ', O.QUANTITY) AS "Part Information:"
FROM
  REPAIR R
  INNER JOIN VEHICLE V ON
    V.VID = R.VEHICLEID
  INNER JOIN CUSTOMER C ON
    C.VEHICLEID = V.VID
  INNER JOIN EMPLOYEE E ON
    E.EID = R.EMPLOYEEID
  INNER JOIN ORDERS O ON
    O.OID = R.ORDERID
  WHERE
    REPAIRDATE BETWEEN (TO_DATE('{$REPAIR_DATE}', 'YYYY MM DD'),
    TO_DATE('{$REPAIR_DATE2}', 'YYYY MM DD')) AND
    UPPER (CONCAT (C.FIRSTNAME, ' ', C.LASTNAME)) LIKE UPPER('%{$REPAIR_SB}%');

--Work History per Employee
WITH
	EMPLOYEE_LABOR AS(
		SELECT
			SUM(R.LABOR) AS LABOR,
			R.EMPLOYEEID AS EMPLOYEEID
		FROM
			REPAIR R
			INNER JOIN EMPLOYEE E ON
				R.EMPLOYEEID = E.EID
		WHERE
			UPPER (CONCAT (E.FIRSTNAME, ' ', E.LASTNAME)) LIKE UPPER ('%{$EMPLOYEE_SB}%')
    GROUP BY
      R.EMPLOYEEID
	)
SELECT
	CONCAT (E.FIRSTNAME, ' ', E.LASTNAME) AS "Employee Name:",
	(EL.LABOR * E.HOURLYRATE) AS "Earnings:",
	COUNT(R.RID) AS "Repairs Made:"
FROM
	EMPLOYEE E
	INNER JOIN REPAIR R ON
		R.EMPLOYEEID = E.EID
	INNER JOIN LOCATION L ON
		L.LID = R.LOCATIONID
	INNER JOIN EMPLOYEE_LABOR EL ON
		EL.EMPLOYEEID = E.EID
WHERE
	UPPER(CONCAT(E.FIRSTNAME, ' ', E.LASTNAME)) LIKE UPPER('%{$EMPLOYEE_SB}%')  AND
	REPAIRDATE BETWEEN (TO_DATE($PAST_REPAIR_DATE,'YYYY MM DD'),
    TO_DATE($REPAIR_DATE,'YYYY MM DD'));
GROUP BY
  E.HOURLYRATE,
  E.FIRSTNAME,
  E.LASTNAME,
  EL.LABOR
ORDER BY
  E.LASTNAME ASC;

--CUSTOMER LOOKUP
SELECT
	CONCAT (C.FIRSTNAME, ' ', C.LASTNAME) AS "Customer Name:",
  C.PHONENUMBER AS "Phone Number:",
  CONCAT ('Year: ', CAST(V.YEAR AS VARCHAR), ', Make: ' , V.MAKE, ', Model: ' , V.MODEL,
    ', License Plate: ', V.LICENSEPLATE) AS "Vehicle Information:"
FROM
	CUSTOMER C
  INNER JOIN VEHICLE V ON
    V.VID = C.VEHICLEID
WHERE
	UPPER(CONCAT (C.FIRSTNAME, ' ', C.LASTNAME)) LIKE UPPER ('%{$CUSTOMERS_SB}%');

-- LOCATION STATISTICS, NOT VERY USEFUL
WITH
  LOCATION_REPAIRS AS ( --Repairs made per Location
    SELECT
    	*
    FROM
    	REPAIR R
    	INNER JOIN LOCATION L ON
    		L.LID = R.LOCATIONID
    ORDER BY
    	L.NAME ASC
  ),
  LOCATION_EMPLOYEES AS( --Employees per Location
    SELECT
    	*
    FROM
    	EMPLOYEE EMP
    	INNER JOIN REPAIR R ON
    		R.EMPLOYEEID = EMP.EID
    	INNER JOIN LOCATION L ON
    		L.LID = R.LOCATIONID
    ORDER BY
    	L.NAME ASC
  ),
  LOCATION_CUSTOMERS AS( --Customers per Location
    SELECT
    	C.CID AS "Customer ID"
    FROM
    	CUSTOMER C
    	INNER JOIN VEHICLE V ON
    		V.VID = C.VEHICLEID
    	INNER JOIN REPAIR R ON
    		R.VEHICLEID = V.VID
    	INNER JOIN LOCATION L ON
    		L.LID = R.LOCATIONID
    ORDER BY
    	L.NAME ASC
  )
SELECT
  *
FROM
  LOCATION_REPAIRS,
  LOCATION_CUSTOMERS,
  LOCATION_EMPLOYEES;

-- LOCATION STATISTICS
SELECT
  L.NAME AS "Location Name:",
  CONCAT ('Customer Name: ', CONCAT(C.FIRSTNAME, ' ', C.LASTNAME), ', Phone Number: ', C.PHONENUMBER) AS "Customer Information:",
  CONCAT ('Year: ', CAST(V.YEAR AS VARCHAR), ', Make: ' , V.MAKE, ', Model: ' , V.MODEL,
    ', License Plate: ', V.LICENSEPLATE) AS "Vehicle Information:",
  CONCAT ('Repair ID: ', R.RID, ', Repair Date: ', R.REPAIRDATE, ', Repair Labor: ', R.LABOR, ' Hours') AS "Repair Information:"
FROM
  LOCATION L
  INNER JOIN REPAIR R ON
    R.LOCATIONID = L.LID
  INNER JOIN EMPLOYEE E
    ON E.EID = R.EMPLOYEEID
  INNER JOIN VEHICLE V
    ON V.VID = R.VEHICLEID
  INNER JOIN ORDERS O
    ON O.OID = R.ORDERID
  INNER JOIN CUSTOMER C
    ON C.VEHICLEID = R.VEHICLEID
ORDER BY
  L.NAME ASC;

-- LOCATION STATISTICS WITH SEARCH BOX
SELECT
  L.NAME,
  CONCAT ('Customer Name: ', CONCAT(C.FIRSTNAME, ' ', C.LASTNAME), ', Phone Number: ', C.PHONENUMBER),
  CONCAT ('Year: ', CAST(V.YEAR AS VARCHAR), ', Make: ' , V.MAKE, ', Model: ' , V.MODEL,
    ', License Plate: ', V.LICENSEPLATE),
  CONCAT ('Repair ID: ', R.RID, ', Repair Date: ', R.REPAIRDATE, ', Repair Labor: ', R.LABOR, ' Hours')
FROM
  LOCATION L
  INNER JOIN REPAIR R ON
    R.LOCATIONID = L.LID
  INNER JOIN EMPLOYEE E
    ON E.EID = R.EMPLOYEEID
  INNER JOIN VEHICLE V
    ON V.VID = R.VEHICLEID
  INNER JOIN ORDERS O
    ON O.OID = R.ORDERID
  INNER JOIN CUSTOMER C
    ON C.VEHICLEID = R.VEHICLEID
WHERE
  UPPER(L.NAME) LIKE UPPER ('%{$LOCATION_SB}%')
ORDER BY
  L.NAME ASC;
